
-- Drop and recreate DBTEST
DROP USER DBTEST CASCADE;

CREATE USER DBTEST
  IDENTIFIED BY DBTEST
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
-- Grant roles for DBTEST 
GRANT CONNECT TO DBTEST;
GRANT RESOURCE TO DBTEST;
  
-- Grant system privilegies for DBTEST   
GRANT ALTER SESSION TO DBTEST;
GRANT CREATE JOB TO DBTEST;
GRANT CREATE MATERIALIZED VIEW TO DBTEST;
GRANT CREATE VIEW TO DBTEST;
GRANT DEBUG ANY PROCEDURE TO DBTEST;
GRANT DEBUG CONNECT SESSION TO DBTEST;
GRANT MANAGE SCHEDULER TO DBTEST;
GRANT SELECT ANY DICTIONARY TO DBTEST;
GRANT UNLIMITED TABLESPACE TO DBTEST;
